---
description: "Sensu Slack Handler"
builds:
- platform: "linux"
  arch: "amd64"
  asset_filename: "sensu-slack-handler_#{version}_linux_amd64.tar.gz" 
  sha_filename: "sensu-slack-handler_#{version}_sha512-checksums.txt" 
  filter:
  -  "System.OS == linux"
  -  "System.Arch == amd64"

- platform: "linux"
  arch: "386"
  asset_filename: "sensu-slack-handler_#{version}_linux_386.tar.gz" 
  sha_filename: "sensu-slack-handler_#{version}_sha512-checksums.txt" 
  filter:
  -  "System.OS == linux"
  -  "System.Arch == 386"

- platform: "linux"
  arch: "arm64"
  asset_filename: "sensu-slack-handler_#{version}_linux_arm64.tar.gz" 
  sha_filename: "sensu-slack-handler_#{version}_sha512-checksums.txt" 
  filter:
  -  "System.OS == linux"
  -  "System.Arch == arm64"

- platform: "linux"
  arch: "armv7"
  asset_filename: "sensu-slack-handler_#{version}_linux_armv7.tar.gz" 
  sha_filename: "sensu-slack-handler_#{version}_sha512-checksums.txt" 
  filter:
  -  "System.OS == linux"
  -  "System.Arch == armv7"


- platform: "OSX"
  arch: "amd64"
  asset_filename: "sensu-slack-handler_#{version}_darwin_amd64.tar.gz" 
  sha_filename: "sensu-slack-handler_#{version}_sha512-checksums.txt" 
  filter:
  -  "System.OS == darwin"
  -  "System.Arch == amd64"

- platform: "OSX"
  arch: "386"
  asset_filename: "sensu-slack-handler_#{version}_darwin_386.tar.gz" 
  sha_filename: "sensu-slack-handler_#{version}_sha512-checksums.txt" 
  filter:
  -  "System.OS == darwin"
  -  "System.Arch == 386"

- platform: "Windows"
  arch: "amd64"
  asset_filename: "sensu-slack-handler_#{version}_windows_amd64.tar.gz" 
  sha_filename: "sensu-slack-handler_#{version}_sha512-checksums.txt" 
  filter:
  -  "System.OS == darwin"
  -  "System.Arch == amd64"

...

